#ifndef _REG_BLOCKS_CSI_WRAP_H_
#define _REG_BLOCKS_CSI_WRAP_H_

/******************************************/
/*           Module Definition            */
/******************************************/
struct REG_SENSOR_PHY_2L_T {
	union REG_SENSOR_PHY_2L_00              REG_00;
	union REG_SENSOR_PHY_2L_04              REG_04;
	union REG_SENSOR_PHY_2L_08              REG_08;
	union REG_SENSOR_PHY_2L_0C              REG_0C;
	union REG_SENSOR_PHY_2L_10              REG_10;
	uint32_t                                _resv_0x14[3];
	union REG_SENSOR_PHY_2L_20              REG_20;
	union REG_SENSOR_PHY_2L_24              REG_24;
	union REG_SENSOR_PHY_2L_28              REG_28;
	uint32_t                                _resv_0x2c[1];
	union REG_SENSOR_PHY_2L_30              REG_30;
	union REG_SENSOR_PHY_2L_34              REG_34;
	union REG_SENSOR_PHY_2L_38              REG_38;
	union REG_SENSOR_PHY_2L_3C              REG_3C;
	union REG_SENSOR_PHY_2L_40              REG_40;
	union REG_SENSOR_PHY_2L_44              REG_44;
	union REG_SENSOR_PHY_2L_48              REG_48;
	union REG_SENSOR_PHY_2L_4C              REG_4C;
	union REG_SENSOR_PHY_2L_50              REG_50;
	union REG_SENSOR_PHY_2L_54              REG_54;
	uint32_t                                _resv_0x58[14];
	union REG_SENSOR_PHY_2L_DBG_90          DBG_90;
	union REG_SENSOR_PHY_2L_DBG_94          DBG_94;
	union REG_SENSOR_PHY_2L_STATUS_98       STATUS_98;
	union REG_SENSOR_PHY_2L_STATUS_9C       STATUS_9C;
	uint32_t                                _resv_0xa0[24];
	union REG_SENSOR_PHY_2L_D0_0            D0_0;
	union REG_SENSOR_PHY_2L_D0_1            D0_1;
	union REG_SENSOR_PHY_2L_D0_2            D0_2;
	union REG_SENSOR_PHY_2L_D0_3            D0_3;
	union REG_SENSOR_PHY_2L_D0_4            D0_4;
	union REG_SENSOR_PHY_2L_D0_5            D0_5;
	union REG_SENSOR_PHY_2L_D0_6            D0_6;
	union REG_SENSOR_PHY_2L_D0_7            D0_7;
	union REG_SENSOR_PHY_2L_D0_8            D0_8;
	union REG_SENSOR_PHY_2L_D0_9            D0_9;
	union REG_SENSOR_PHY_2L_D0_A            D0_A;
	union REG_SENSOR_PHY_2L_D0_B            D0_B;
	uint32_t                                _resv_0x130[4];
	union REG_SENSOR_PHY_2L_D1_0            D1_0;
	union REG_SENSOR_PHY_2L_D1_1            D1_1;
	union REG_SENSOR_PHY_2L_D1_2            D1_2;
	union REG_SENSOR_PHY_2L_D1_3            D1_3;
	union REG_SENSOR_PHY_2L_D1_4            D1_4;
	union REG_SENSOR_PHY_2L_D1_5            D1_5;
	union REG_SENSOR_PHY_2L_D1_6            D1_6;
	union REG_SENSOR_PHY_2L_D1_7            D1_7;
	union REG_SENSOR_PHY_2L_D1_8            D1_8;
	union REG_SENSOR_PHY_2L_D1_9            D1_9;
	union REG_SENSOR_PHY_2L_D1_A            D1_A;
	union REG_SENSOR_PHY_2L_D1_B            D1_B;
};

/******************************************/
/*           Module Definition            */
/******************************************/
struct REG_SENSOR_PHY_4L_T {
	union REG_SENSOR_PHY_4L_00              REG_00;
	union REG_SENSOR_PHY_4L_04              REG_04;
	union REG_SENSOR_PHY_4L_08              REG_08;
	union REG_SENSOR_PHY_4L_0C              REG_0C;
	union REG_SENSOR_PHY_4L_10              REG_10;
	uint32_t                                _resv_0x14[3];
	union REG_SENSOR_PHY_4L_20              REG_20;
	union REG_SENSOR_PHY_4L_24              REG_24;
	union REG_SENSOR_PHY_4L_28              REG_28;
	uint32_t                                _resv_0x2c[1];
	union REG_SENSOR_PHY_4L_30              REG_30;
	union REG_SENSOR_PHY_4L_34              REG_34;
	union REG_SENSOR_PHY_4L_38              REG_38;
	union REG_SENSOR_PHY_4L_3C              REG_3C;
	union REG_SENSOR_PHY_4L_40              REG_40;
	union REG_SENSOR_PHY_4L_44              REG_44;
	union REG_SENSOR_PHY_4L_48              REG_48;
	union REG_SENSOR_PHY_4L_4C              REG_4C;
	union REG_SENSOR_PHY_4L_50              REG_50;
	union REG_SENSOR_PHY_4L_54              REG_54;
	union REG_SENSOR_PHY_4L_58              REG_58;
	union REG_SENSOR_PHY_4L_5C              REG_5C;
	union REG_SENSOR_PHY_4L_60              REG_60;
	union REG_SENSOR_PHY_4L_64              REG_64;
	uint32_t                                _resv_0x68[10];
	union REG_SENSOR_PHY_4L_DBG_90          DBG_90;
	union REG_SENSOR_PHY_4L_DBG_94          DBG_94;
	union REG_SENSOR_PHY_4L_STATUS_98       STATUS_98;
	union REG_SENSOR_PHY_4L_STATUS_9C       STATUS_9C;
	uint32_t                                _resv_0xa0[1];
	union REG_SENSOR_PHY_4L_STATUS_A4       STATUS_A4;
	union REG_SENSOR_PHY_4L_STATUS_A8       STATUS_A8;
	uint32_t                                _resv_0xac[21];
	union REG_SENSOR_PHY_4L_D0_0            D0_0;
	union REG_SENSOR_PHY_4L_D0_1            D0_1;
	union REG_SENSOR_PHY_4L_D0_2            D0_2;
	union REG_SENSOR_PHY_4L_D0_3            D0_3;
	union REG_SENSOR_PHY_4L_D0_4            D0_4;
	union REG_SENSOR_PHY_4L_D0_5            D0_5;
	union REG_SENSOR_PHY_4L_D0_6            D0_6;
	union REG_SENSOR_PHY_4L_D0_7            D0_7;
	union REG_SENSOR_PHY_4L_D0_8            D0_8;
	union REG_SENSOR_PHY_4L_D0_9            D0_9;
	union REG_SENSOR_PHY_4L_D0_A            D0_A;
	union REG_SENSOR_PHY_4L_D0_B            D0_B;
	uint32_t                                _resv_0x130[4];
	union REG_SENSOR_PHY_4L_D1_0            D1_0;
	union REG_SENSOR_PHY_4L_D1_1            D1_1;
	union REG_SENSOR_PHY_4L_D1_2            D1_2;
	union REG_SENSOR_PHY_4L_D1_3            D1_3;
	union REG_SENSOR_PHY_4L_D1_4            D1_4;
	union REG_SENSOR_PHY_4L_D1_5            D1_5;
	union REG_SENSOR_PHY_4L_D1_6            D1_6;
	union REG_SENSOR_PHY_4L_D1_7            D1_7;
	union REG_SENSOR_PHY_4L_D1_8            D1_8;
	union REG_SENSOR_PHY_4L_D1_9            D1_9;
	union REG_SENSOR_PHY_4L_D1_A            D1_A;
	union REG_SENSOR_PHY_4L_D1_B            D1_B;
	uint32_t                                _resv_0x170[4];
	union REG_SENSOR_PHY_4L_D2_0            D2_0;
	union REG_SENSOR_PHY_4L_D2_1            D2_1;
	union REG_SENSOR_PHY_4L_D2_2            D2_2;
	union REG_SENSOR_PHY_4L_D2_3            D2_3;
	union REG_SENSOR_PHY_4L_D2_4            D2_4;
	union REG_SENSOR_PHY_4L_D2_5            D2_5;
	union REG_SENSOR_PHY_4L_D2_6            D2_6;
	union REG_SENSOR_PHY_4L_D2_7            D2_7;
	union REG_SENSOR_PHY_4L_D2_8            D2_8;
	union REG_SENSOR_PHY_4L_D2_9            D2_9;
	union REG_SENSOR_PHY_4L_D2_A            D2_A;
	union REG_SENSOR_PHY_4L_D2_B            D2_B;
	uint32_t                                _resv_0x1b0[4];
	union REG_SENSOR_PHY_4L_D3_0            D3_0;
	union REG_SENSOR_PHY_4L_D3_1            D3_1;
	union REG_SENSOR_PHY_4L_D3_2            D3_2;
	union REG_SENSOR_PHY_4L_D3_3            D3_3;
	union REG_SENSOR_PHY_4L_D3_4            D3_4;
	union REG_SENSOR_PHY_4L_D3_5            D3_5;
	union REG_SENSOR_PHY_4L_D3_6            D3_6;
	union REG_SENSOR_PHY_4L_D3_7            D3_7;
	union REG_SENSOR_PHY_4L_D3_8            D3_8;
	union REG_SENSOR_PHY_4L_D3_9            D3_9;
	union REG_SENSOR_PHY_4L_D3_A            D3_A;
	union REG_SENSOR_PHY_4L_D3_B            D3_B;
};

/******************************************/
/*           Module Definition            */
/******************************************/
struct REG_SENSOR_PHY_TOP_T {
	union REG_SENSOR_PHY_TOP_00             REG_00;
	union REG_SENSOR_PHY_TOP_04             REG_04;
	union REG_SENSOR_PHY_TOP_08             REG_08;
	union REG_SENSOR_PHY_TOP_0C             REG_0C;
	union REG_SENSOR_PHY_TOP_10             REG_10;
	uint32_t                                _resv_0x14[3];
	union REG_SENSOR_PHY_TOP_20             REG_20;
	union REG_SENSOR_PHY_TOP_24             REG_24;
	uint32_t                                _resv_0x28[1];
	union REG_SENSOR_PHY_TOP_2C             REG_2C;
	union REG_SENSOR_PHY_TOP_30             REG_30;
	union REG_SENSOR_PHY_TOP_34             REG_34;
	union REG_SENSOR_PHY_TOP_38             REG_38;
	union REG_SENSOR_PHY_TOP_3C             REG_3C;
	union REG_SENSOR_PHY_TOP_40             REG_40;
	union REG_SENSOR_PHY_TOP_44             REG_44;
	union REG_SENSOR_PHY_TOP_48             REG_48;
	uint32_t                                _resv_0x4c[9];
	union REG_SENSOR_PHY_TOP_70             REG_70;
	union REG_SENSOR_PHY_TOP_74             REG_74;
	uint32_t                                _resv_0x78[1];
	union REG_SENSOR_PHY_TOP_7C             REG_7C;
	union REG_SENSOR_PHY_TOP_80             REG_80;
	union REG_SENSOR_PHY_TOP_84             REG_84;
	union REG_SENSOR_PHY_TOP_88             REG_88;
	uint32_t                                _resv_0x8c[1];
	union REG_SENSOR_PHY_TOP_90             REG_90;
	union REG_SENSOR_PHY_TOP_94             REG_94;
	uint32_t                                _resv_0x98[2];
	union REG_SENSOR_PHY_TOP_A0             REG_A0;
	union REG_SENSOR_PHY_TOP_A4             REG_A4;
	union REG_SENSOR_PHY_TOP_A8             REG_A8;
	union REG_SENSOR_PHY_TOP_AC             REG_AC;
	uint32_t                                _resv_0xb0[20];
	union REG_SENSOR_PHY_TOP_DFT_100        DFT_100;
	union REG_SENSOR_PHY_TOP_DFT_104        DFT_104;
	union REG_SENSOR_PHY_TOP_DFT_108        DFT_108;
	union REG_SENSOR_PHY_TOP_DFT_10C        DFT_10C;
	union REG_SENSOR_PHY_TOP_DFT_110        DFT_110;
	union REG_SENSOR_PHY_TOP_DFT_114        DFT_114;
	uint32_t                                _resv_0x118[1];
	union REG_SENSOR_PHY_TOP_DFT_11C        DFT_11C;
	union REG_SENSOR_PHY_TOP_DBG_12         DBG_12;
	uint32_t                                _resv_0x124[55];
	union REG_SENSOR_PHY_TOP_TEST_0         TEST_0;
	union REG_SENSOR_PHY_TOP_TEST_1         TEST_1;
	union REG_SENSOR_PHY_TOP_TEST_2         TEST_2;
	union REG_SENSOR_PHY_TOP_TEST_3         TEST_3;
	union REG_SENSOR_PHY_TOP_TEST_4         TEST_4;
	union REG_SENSOR_PHY_TOP_TEST_5         TEST_5;
	union REG_SENSOR_PHY_TOP_TEST_6         TEST_6;
	union REG_SENSOR_PHY_TOP_TEST_7         TEST_7;
	union REG_SENSOR_PHY_TOP_TEST_8         TEST_8;
	union REG_SENSOR_PHY_TOP_TEST_9         TEST_9;
	union REG_SENSOR_PHY_TOP_TEST_A         TEST_A;
	union REG_SENSOR_PHY_TOP_TEST_B         TEST_B;
	uint32_t                                _resv_0x230[12];
	union REG_SENSOR_PHY_TOP_DUMMY_D0       DUMMY_D0;
	union REG_SENSOR_PHY_TOP_DUMMY_D1       DUMMY_D1;
	union REG_SENSOR_PHY_TOP_DUMMY_D2       DUMMY_D2;
	union REG_SENSOR_PHY_TOP_DUMMY_D3       DUMMY_D3;
	union REG_SENSOR_PHY_TOP_DUMMY_D4       DUMMY_D4;
	union REG_SENSOR_PHY_TOP_DUMMY_D5       DUMMY_D5;
	union REG_SENSOR_PHY_TOP_DUMMY_D6       DUMMY_D6;
	union REG_SENSOR_PHY_TOP_DUMMY_D7       DUMMY_D7;
};

#endif // _REG_BLOCKS_CSI_WRAP_H_
