#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

ifdef CONFIG_VIDEO_CVITEK
obj-y += cvi_disp.o cvi_mipi.o scaler.o reg.o vip_sys.o dsi_phy.o cvi_i80.o
obj-$(CONFIG_DISPLAY_CVITEK_LVDS) += cvi_lvds.o
endif
