/*
 * Copyright (c) 2019, Cvitek. All rights reserved.
 *
 */
// $Date: Wed, 27 Nov 2019 08:24:45 PM $
#define  fmux_gpio_REG_IOCTRL_JTAG_CPU_TCK  0x0
#define  fmux_gpio_REG_IOCTRL_SDIO0_CD  0x4
#define  fmux_gpio_REG_IOCTRL_RSTN  0x8
#define  fmux_gpio_REG_IOCTRL_JTAG_CPU_TRST  0xc
#define  fmux_gpio_REG_IOCTRL_UART0_RX  0x10
#define  fmux_gpio_REG_IOCTRL_SDIO0_PWR_EN  0x14
#define  fmux_gpio_REG_IOCTRL_UART0_TX  0x18
#define  fmux_gpio_REG_IOCTRL_JTAG_CPU_TMS  0x1c
#define  fmux_gpio_REG_IOCTRL_EMMC_CLK  0x20
#define  fmux_gpio_REG_IOCTRL_EMMC_RSTN  0x24
#define  fmux_gpio_REG_IOCTRL_EMMC_CMD  0x28
#define  fmux_gpio_REG_IOCTRL_EMMC_DAT1  0x2c
#define  fmux_gpio_REG_IOCTRL_EMMC_DAT0  0x30
#define  fmux_gpio_REG_IOCTRL_EMMC_DAT2  0x34
#define  fmux_gpio_REG_IOCTRL_EMMC_DAT3  0x38
#define  fmux_gpio_REG_IOCTRL_SDIO0_CMD  0x3c
#define  fmux_gpio_REG_IOCTRL_SDIO0_CLK  0x40
#define  fmux_gpio_REG_IOCTRL_SDIO0_D0  0x44
#define  fmux_gpio_REG_IOCTRL_SDIO0_D1  0x48
#define  fmux_gpio_REG_IOCTRL_SDIO0_D2  0x4c
#define  fmux_gpio_REG_IOCTRL_SDIO0_D3  0x50
#define  fmux_gpio_REG_IOCTRL_RMII0_TXEN  0x54
#define  fmux_gpio_REG_IOCTRL_RMII0_TXD1  0x58
#define  fmux_gpio_REG_IOCTRL_RMII0_TXD0  0x5c
#define  fmux_gpio_REG_IOCTRL_RMII0_REFCLKI  0x60
#define  fmux_gpio_REG_IOCTRL_RMII0_MDIO  0x64
#define  fmux_gpio_REG_IOCTRL_RMII0_MDCK  0x68
#define  fmux_gpio_REG_IOCTRL_RMII0_RST  0x6c
#define  fmux_gpio_REG_IOCTRL_RMII0_RXD0  0x70
#define  fmux_gpio_REG_IOCTRL_RMII0_RXD1  0x74
#define  fmux_gpio_REG_IOCTRL_RMII0_RXDV  0x78
#define  fmux_gpio_REG_IOCTRL_RTC_MODE  0x7c
#define  fmux_gpio_REG_IOCTRL_PWR_WAKEUP0  0x80
#define  fmux_gpio_REG_IOCTRL_PWR_BUTTON1  0x84
#define  fmux_gpio_REG_IOCTRL_PWR_WAKEUP1  0x88
#define  fmux_gpio_REG_IOCTRL_PWR_BUTTON0  0x8c
#define  fmux_gpio_REG_IOCTRL_PWR_VBAT_DET  0x90
#define  fmux_gpio_REG_IOCTRL_PWR_ON  0x94
#define  fmux_gpio_REG_IOCTRL_PWM2  0x98
#define  fmux_gpio_REG_IOCTRL_PWM0_BUCK  0x9c
#define  fmux_gpio_REG_IOCTRL_PWM3  0xa0
#define  fmux_gpio_REG_IOCTRL_PWM1  0xa4
#define  fmux_gpio_REG_IOCTRL_SPI0_SDI  0xa8
#define  fmux_gpio_REG_IOCTRL_SPI0_SDO  0xac
#define  fmux_gpio_REG_IOCTRL_SPI0_SCK  0xb0
#define  fmux_gpio_REG_IOCTRL_SPI0_CS_X  0xb4
#define  fmux_gpio_REG_IOCTRL_IIC2_SCL  0xb8
#define  fmux_gpio_REG_IOCTRL_IIC1_SCL  0xbc
#define  fmux_gpio_REG_IOCTRL_IIC1_SDA  0xc0
#define  fmux_gpio_REG_IOCTRL_UART2_TX  0xc4
#define  fmux_gpio_REG_IOCTRL_IIC2_SDA  0xc8
#define  fmux_gpio_REG_IOCTRL_UART1_RTS  0xcc
#define  fmux_gpio_REG_IOCTRL_UART2_RTS  0xd0
#define  fmux_gpio_REG_IOCTRL_UART2_RX  0xd4
#define  fmux_gpio_REG_IOCTRL_UART1_TX  0xd8
#define  fmux_gpio_REG_IOCTRL_UART1_CTS  0xdc
#define  fmux_gpio_REG_IOCTRL_BOOT_MS  0xe0
#define  fmux_gpio_REG_IOCTRL_UART2_CTS  0xe4
#define  fmux_gpio_REG_IOCTRL_ADC1  0xe8
#define  fmux_gpio_REG_IOCTRL_UART1_RX  0xec
#define  fmux_gpio_REG_IOCTRL_USB_ID  0xf0
#define  fmux_gpio_REG_IOCTRL_USB_VBUS_DET  0xf4
#define  fmux_gpio_REG_IOCTRL_USB_VBUS_EN  0xf8
#define  fmux_gpio_REG_IOCTRL_CLK32K  0xfc
#define  fmux_gpio_REG_IOCTRL_CLK25M  0x100
#define  fmux_gpio_REG_IOCTRL_XTAL_XIN_XI  0x104
#define  fmux_gpio_REG_IOCTRL_VO_DATA1  0x108
#define  fmux_gpio_REG_IOCTRL_VO_DATA0  0x10c
#define  fmux_gpio_REG_IOCTRL_PAD_MIPI_TXM4  0x110
#define  fmux_gpio_REG_IOCTRL_PAD_MIPI_TXP4  0x114
#define  fmux_gpio_REG_IOCTRL_PAD_MIPI_TXM3  0x118
#define  fmux_gpio_REG_IOCTRL_PAD_MIPI_TXP3  0x11c
#define  fmux_gpio_REG_IOCTRL_PAD_MIPI_TXM2  0x120
#define  fmux_gpio_REG_IOCTRL_PAD_MIPI_TXP2  0x124
#define  fmux_gpio_REG_IOCTRL_PAD_MIPI_TXM1  0x128
#define  fmux_gpio_REG_IOCTRL_PAD_MIPI_TXP1  0x12c
#define  fmux_gpio_REG_IOCTRL_PAD_MIPI_TXM0  0x130
#define  fmux_gpio_REG_IOCTRL_PAD_MIPI_TXP0  0x134
#define  fmux_gpio_REG_IOCTRL_MIPIRX1_PAD0P  0x138
#define  fmux_gpio_REG_IOCTRL_MIPIRX1_PAD0N  0x13c
#define  fmux_gpio_REG_IOCTRL_MIPIRX1_PAD1P  0x140
#define  fmux_gpio_REG_IOCTRL_MIPIRX1_PAD1N  0x144
#define  fmux_gpio_REG_IOCTRL_MIPIRX1_PAD2P  0x148
#define  fmux_gpio_REG_IOCTRL_MIPIRX1_PAD2N  0x14c
#define  fmux_gpio_REG_IOCTRL_MIPIRX1_PAD3P  0x150
#define  fmux_gpio_REG_IOCTRL_MIPIRX1_PAD3N  0x154
#define  fmux_gpio_REG_IOCTRL_MIPIRX1_PAD4P  0x158
#define  fmux_gpio_REG_IOCTRL_MIPIRX1_PAD4N  0x15c
#define  fmux_gpio_REG_IOCTRL_MIPIRX0_PAD4N  0x160
#define  fmux_gpio_REG_IOCTRL_MIPIRX0_PAD4P  0x164
#define  fmux_gpio_REG_IOCTRL_MIPIRX0_PAD3N  0x168
#define  fmux_gpio_REG_IOCTRL_MIPIRX0_PAD3P  0x16c
#define  fmux_gpio_REG_IOCTRL_MIPIRX0_PAD2N  0x170
#define  fmux_gpio_REG_IOCTRL_MIPIRX0_PAD2P  0x174
#define  fmux_gpio_REG_IOCTRL_MIPIRX0_PAD1N  0x178
#define  fmux_gpio_REG_IOCTRL_MIPIRX0_PAD1P  0x17c
#define  fmux_gpio_REG_IOCTRL_MIPIRX0_PAD0N  0x180
#define  fmux_gpio_REG_IOCTRL_MIPIRX0_PAD0P  0x184
#define  fmux_gpio_REG_IOCTRL_VI_DATA22  0x188
#define  fmux_gpio_REG_IOCTRL_VI_DATA20  0x18c
#define  fmux_gpio_REG_IOCTRL_VI_DATA21  0x190
#define  fmux_gpio_REG_IOCTRL_CAM_PD0  0x194
#define  fmux_gpio_REG_IOCTRL_VI_DATA19  0x198
#define  fmux_gpio_REG_IOCTRL_IIC0_SDA  0x19c
#define  fmux_gpio_REG_IOCTRL_CAM_MCLK0  0x1a0
#define  fmux_gpio_REG_IOCTRL_IIC3_SCL  0x1a4
#define  fmux_gpio_REG_IOCTRL_VI_DATA24  0x1a8
#define  fmux_gpio_REG_IOCTRL_CAM_RST0  0x1ac
#define  fmux_gpio_REG_IOCTRL_VI_DATA23  0x1b0
#define  fmux_gpio_REG_IOCTRL_IIC3_SDA  0x1b4
#define  fmux_gpio_REG_IOCTRL_IIC0_SCL  0x1b8
#define  fmux_gpio_funcsel_JTAG_CPU_TCK   0x0
#define  fmux_gpio_funcsel_JTAG_CPU_TCK_OFFSET 0
#define  fmux_gpio_funcsel_JTAG_CPU_TCK_MASK   0x7
#define  fmux_gpio_funcsel_SDIO0_CD   0x4
#define  fmux_gpio_funcsel_SDIO0_CD_OFFSET 0
#define  fmux_gpio_funcsel_SDIO0_CD_MASK   0x7
#define  fmux_gpio_funcsel_RSTN   0x8
#define  fmux_gpio_funcsel_RSTN_OFFSET 0
#define  fmux_gpio_funcsel_RSTN_MASK   0x7
#define  fmux_gpio_funcsel_JTAG_CPU_TRST   0xc
#define  fmux_gpio_funcsel_JTAG_CPU_TRST_OFFSET 0
#define  fmux_gpio_funcsel_JTAG_CPU_TRST_MASK   0x7
#define  fmux_gpio_funcsel_UART0_RX   0x10
#define  fmux_gpio_funcsel_UART0_RX_OFFSET 0
#define  fmux_gpio_funcsel_UART0_RX_MASK   0x7
#define  fmux_gpio_funcsel_SDIO0_PWR_EN   0x14
#define  fmux_gpio_funcsel_SDIO0_PWR_EN_OFFSET 0
#define  fmux_gpio_funcsel_SDIO0_PWR_EN_MASK   0x7
#define  fmux_gpio_funcsel_UART0_TX   0x18
#define  fmux_gpio_funcsel_UART0_TX_OFFSET 0
#define  fmux_gpio_funcsel_UART0_TX_MASK   0x7
#define  fmux_gpio_funcsel_JTAG_CPU_TMS   0x1c
#define  fmux_gpio_funcsel_JTAG_CPU_TMS_OFFSET 0
#define  fmux_gpio_funcsel_JTAG_CPU_TMS_MASK   0x7
#define  fmux_gpio_funcsel_EMMC_CLK   0x20
#define  fmux_gpio_funcsel_EMMC_CLK_OFFSET 0
#define  fmux_gpio_funcsel_EMMC_CLK_MASK   0x7
#define  fmux_gpio_funcsel_EMMC_RSTN   0x24
#define  fmux_gpio_funcsel_EMMC_RSTN_OFFSET 0
#define  fmux_gpio_funcsel_EMMC_RSTN_MASK   0x7
#define  fmux_gpio_funcsel_EMMC_CMD   0x28
#define  fmux_gpio_funcsel_EMMC_CMD_OFFSET 0
#define  fmux_gpio_funcsel_EMMC_CMD_MASK   0x7
#define  fmux_gpio_funcsel_EMMC_DAT1   0x2c
#define  fmux_gpio_funcsel_EMMC_DAT1_OFFSET 0
#define  fmux_gpio_funcsel_EMMC_DAT1_MASK   0x7
#define  fmux_gpio_funcsel_EMMC_DAT0   0x30
#define  fmux_gpio_funcsel_EMMC_DAT0_OFFSET 0
#define  fmux_gpio_funcsel_EMMC_DAT0_MASK   0x7
#define  fmux_gpio_funcsel_EMMC_DAT2   0x34
#define  fmux_gpio_funcsel_EMMC_DAT2_OFFSET 0
#define  fmux_gpio_funcsel_EMMC_DAT2_MASK   0x7
#define  fmux_gpio_funcsel_EMMC_DAT3   0x38
#define  fmux_gpio_funcsel_EMMC_DAT3_OFFSET 0
#define  fmux_gpio_funcsel_EMMC_DAT3_MASK   0x7
#define  fmux_gpio_funcsel_SDIO0_CMD   0x3c
#define  fmux_gpio_funcsel_SDIO0_CMD_OFFSET 0
#define  fmux_gpio_funcsel_SDIO0_CMD_MASK   0x7
#define  fmux_gpio_funcsel_SDIO0_CLK   0x40
#define  fmux_gpio_funcsel_SDIO0_CLK_OFFSET 0
#define  fmux_gpio_funcsel_SDIO0_CLK_MASK   0x7
#define  fmux_gpio_funcsel_SDIO0_D0   0x44
#define  fmux_gpio_funcsel_SDIO0_D0_OFFSET 0
#define  fmux_gpio_funcsel_SDIO0_D0_MASK   0x7
#define  fmux_gpio_funcsel_SDIO0_D1   0x48
#define  fmux_gpio_funcsel_SDIO0_D1_OFFSET 0
#define  fmux_gpio_funcsel_SDIO0_D1_MASK   0x7
#define  fmux_gpio_funcsel_SDIO0_D2   0x4c
#define  fmux_gpio_funcsel_SDIO0_D2_OFFSET 0
#define  fmux_gpio_funcsel_SDIO0_D2_MASK   0x7
#define  fmux_gpio_funcsel_SDIO0_D3   0x50
#define  fmux_gpio_funcsel_SDIO0_D3_OFFSET 0
#define  fmux_gpio_funcsel_SDIO0_D3_MASK   0x7
#define  fmux_gpio_funcsel_RMII0_TXEN   0x54
#define  fmux_gpio_funcsel_RMII0_TXEN_OFFSET 0
#define  fmux_gpio_funcsel_RMII0_TXEN_MASK   0x7
#define  fmux_gpio_funcsel_RMII0_TXD1   0x58
#define  fmux_gpio_funcsel_RMII0_TXD1_OFFSET 0
#define  fmux_gpio_funcsel_RMII0_TXD1_MASK   0x7
#define  fmux_gpio_funcsel_RMII0_TXD0   0x5c
#define  fmux_gpio_funcsel_RMII0_TXD0_OFFSET 0
#define  fmux_gpio_funcsel_RMII0_TXD0_MASK   0x7
#define  fmux_gpio_funcsel_RMII0_REFCLKI   0x60
#define  fmux_gpio_funcsel_RMII0_REFCLKI_OFFSET 0
#define  fmux_gpio_funcsel_RMII0_REFCLKI_MASK   0x7
#define  fmux_gpio_funcsel_RMII0_MDIO   0x64
#define  fmux_gpio_funcsel_RMII0_MDIO_OFFSET 0
#define  fmux_gpio_funcsel_RMII0_MDIO_MASK   0x7
#define  fmux_gpio_funcsel_RMII0_MDCK   0x68
#define  fmux_gpio_funcsel_RMII0_MDCK_OFFSET 0
#define  fmux_gpio_funcsel_RMII0_MDCK_MASK   0x7
#define  fmux_gpio_funcsel_RMII0_RST   0x6c
#define  fmux_gpio_funcsel_RMII0_RST_OFFSET 0
#define  fmux_gpio_funcsel_RMII0_RST_MASK   0x7
#define  fmux_gpio_funcsel_RMII0_RXD0   0x70
#define  fmux_gpio_funcsel_RMII0_RXD0_OFFSET 0
#define  fmux_gpio_funcsel_RMII0_RXD0_MASK   0x7
#define  fmux_gpio_funcsel_RMII0_RXD1   0x74
#define  fmux_gpio_funcsel_RMII0_RXD1_OFFSET 0
#define  fmux_gpio_funcsel_RMII0_RXD1_MASK   0x7
#define  fmux_gpio_funcsel_RMII0_RXDV   0x78
#define  fmux_gpio_funcsel_RMII0_RXDV_OFFSET 0
#define  fmux_gpio_funcsel_RMII0_RXDV_MASK   0x7
#define  fmux_gpio_funcsel_RTC_MODE   0x7c
#define  fmux_gpio_funcsel_RTC_MODE_OFFSET 0
#define  fmux_gpio_funcsel_RTC_MODE_MASK   0x7
#define  fmux_gpio_funcsel_PWR_WAKEUP0   0x80
#define  fmux_gpio_funcsel_PWR_WAKEUP0_OFFSET 0
#define  fmux_gpio_funcsel_PWR_WAKEUP0_MASK   0x7
#define  fmux_gpio_funcsel_PWR_BUTTON1   0x84
#define  fmux_gpio_funcsel_PWR_BUTTON1_OFFSET 0
#define  fmux_gpio_funcsel_PWR_BUTTON1_MASK   0x7
#define  fmux_gpio_funcsel_PWR_WAKEUP1   0x88
#define  fmux_gpio_funcsel_PWR_WAKEUP1_OFFSET 0
#define  fmux_gpio_funcsel_PWR_WAKEUP1_MASK   0x7
#define  fmux_gpio_funcsel_PWR_BUTTON0   0x8c
#define  fmux_gpio_funcsel_PWR_BUTTON0_OFFSET 0
#define  fmux_gpio_funcsel_PWR_BUTTON0_MASK   0x7
#define  fmux_gpio_funcsel_PWR_VBAT_DET   0x90
#define  fmux_gpio_funcsel_PWR_VBAT_DET_OFFSET 0
#define  fmux_gpio_funcsel_PWR_VBAT_DET_MASK   0x7
#define  fmux_gpio_funcsel_PWR_ON   0x94
#define  fmux_gpio_funcsel_PWR_ON_OFFSET 0
#define  fmux_gpio_funcsel_PWR_ON_MASK   0x7
#define  fmux_gpio_funcsel_PWM2   0x98
#define  fmux_gpio_funcsel_PWM2_OFFSET 0
#define  fmux_gpio_funcsel_PWM2_MASK   0x7
#define  fmux_gpio_funcsel_PWM0_BUCK   0x9c
#define  fmux_gpio_funcsel_PWM0_BUCK_OFFSET 0
#define  fmux_gpio_funcsel_PWM0_BUCK_MASK   0x7
#define  fmux_gpio_funcsel_PWM3   0xa0
#define  fmux_gpio_funcsel_PWM3_OFFSET 0
#define  fmux_gpio_funcsel_PWM3_MASK   0x7
#define  fmux_gpio_funcsel_PWM1   0xa4
#define  fmux_gpio_funcsel_PWM1_OFFSET 0
#define  fmux_gpio_funcsel_PWM1_MASK   0x7
#define  fmux_gpio_funcsel_SPI0_SDI   0xa8
#define  fmux_gpio_funcsel_SPI0_SDI_OFFSET 0
#define  fmux_gpio_funcsel_SPI0_SDI_MASK   0x7
#define  fmux_gpio_funcsel_SPI0_SDO   0xac
#define  fmux_gpio_funcsel_SPI0_SDO_OFFSET 0
#define  fmux_gpio_funcsel_SPI0_SDO_MASK   0x7
#define  fmux_gpio_funcsel_SPI0_SCK   0xb0
#define  fmux_gpio_funcsel_SPI0_SCK_OFFSET 0
#define  fmux_gpio_funcsel_SPI0_SCK_MASK   0x7
#define  fmux_gpio_funcsel_SPI0_CS_X   0xb4
#define  fmux_gpio_funcsel_SPI0_CS_X_OFFSET 0
#define  fmux_gpio_funcsel_SPI0_CS_X_MASK   0x7
#define  fmux_gpio_funcsel_IIC2_SCL   0xb8
#define  fmux_gpio_funcsel_IIC2_SCL_OFFSET 0
#define  fmux_gpio_funcsel_IIC2_SCL_MASK   0x7
#define  fmux_gpio_funcsel_IIC1_SCL   0xbc
#define  fmux_gpio_funcsel_IIC1_SCL_OFFSET 0
#define  fmux_gpio_funcsel_IIC1_SCL_MASK   0x7
#define  fmux_gpio_funcsel_IIC1_SDA   0xc0
#define  fmux_gpio_funcsel_IIC1_SDA_OFFSET 0
#define  fmux_gpio_funcsel_IIC1_SDA_MASK   0x7
#define  fmux_gpio_funcsel_UART2_TX   0xc4
#define  fmux_gpio_funcsel_UART2_TX_OFFSET 0
#define  fmux_gpio_funcsel_UART2_TX_MASK   0x7
#define  fmux_gpio_funcsel_IIC2_SDA   0xc8
#define  fmux_gpio_funcsel_IIC2_SDA_OFFSET 0
#define  fmux_gpio_funcsel_IIC2_SDA_MASK   0x7
#define  fmux_gpio_funcsel_UART1_RTS   0xcc
#define  fmux_gpio_funcsel_UART1_RTS_OFFSET 0
#define  fmux_gpio_funcsel_UART1_RTS_MASK   0x7
#define  fmux_gpio_funcsel_UART2_RTS   0xd0
#define  fmux_gpio_funcsel_UART2_RTS_OFFSET 0
#define  fmux_gpio_funcsel_UART2_RTS_MASK   0x7
#define  fmux_gpio_funcsel_UART2_RX   0xd4
#define  fmux_gpio_funcsel_UART2_RX_OFFSET 0
#define  fmux_gpio_funcsel_UART2_RX_MASK   0x7
#define  fmux_gpio_funcsel_UART1_TX   0xd8
#define  fmux_gpio_funcsel_UART1_TX_OFFSET 0
#define  fmux_gpio_funcsel_UART1_TX_MASK   0x7
#define  fmux_gpio_funcsel_UART1_CTS   0xdc
#define  fmux_gpio_funcsel_UART1_CTS_OFFSET 0
#define  fmux_gpio_funcsel_UART1_CTS_MASK   0x7
#define  fmux_gpio_funcsel_BOOT_MS   0xe0
#define  fmux_gpio_funcsel_BOOT_MS_OFFSET 0
#define  fmux_gpio_funcsel_BOOT_MS_MASK   0x7
#define  fmux_gpio_funcsel_UART2_CTS   0xe4
#define  fmux_gpio_funcsel_UART2_CTS_OFFSET 0
#define  fmux_gpio_funcsel_UART2_CTS_MASK   0x7
#define  fmux_gpio_funcsel_ADC1   0xe8
#define  fmux_gpio_funcsel_ADC1_OFFSET 0
#define  fmux_gpio_funcsel_ADC1_MASK   0x7
#define  fmux_gpio_funcsel_UART1_RX   0xec
#define  fmux_gpio_funcsel_UART1_RX_OFFSET 0
#define  fmux_gpio_funcsel_UART1_RX_MASK   0x7
#define  fmux_gpio_funcsel_USB_ID   0xf0
#define  fmux_gpio_funcsel_USB_ID_OFFSET 0
#define  fmux_gpio_funcsel_USB_ID_MASK   0x7
#define  fmux_gpio_funcsel_USB_VBUS_DET   0xf4
#define  fmux_gpio_funcsel_USB_VBUS_DET_OFFSET 0
#define  fmux_gpio_funcsel_USB_VBUS_DET_MASK   0x7
#define  fmux_gpio_funcsel_USB_VBUS_EN   0xf8
#define  fmux_gpio_funcsel_USB_VBUS_EN_OFFSET 0
#define  fmux_gpio_funcsel_USB_VBUS_EN_MASK   0x7
#define  fmux_gpio_funcsel_CLK32K   0xfc
#define  fmux_gpio_funcsel_CLK32K_OFFSET 0
#define  fmux_gpio_funcsel_CLK32K_MASK   0x7
#define  fmux_gpio_funcsel_CLK25M   0x100
#define  fmux_gpio_funcsel_CLK25M_OFFSET 0
#define  fmux_gpio_funcsel_CLK25M_MASK   0x7
#define  fmux_gpio_funcsel_XTAL_XIN_XI   0x104
#define  fmux_gpio_funcsel_XTAL_XIN_XI_OFFSET 0
#define  fmux_gpio_funcsel_XTAL_XIN_XI_MASK   0x7
#define  fmux_gpio_funcsel_VO_DATA1   0x108
#define  fmux_gpio_funcsel_VO_DATA1_OFFSET 0
#define  fmux_gpio_funcsel_VO_DATA1_MASK   0x7
#define  fmux_gpio_funcsel_VO_DATA0   0x10c
#define  fmux_gpio_funcsel_VO_DATA0_OFFSET 0
#define  fmux_gpio_funcsel_VO_DATA0_MASK   0x7
#define  fmux_gpio_funcsel_PAD_MIPI_TXM4   0x110
#define  fmux_gpio_funcsel_PAD_MIPI_TXM4_OFFSET 0
#define  fmux_gpio_funcsel_PAD_MIPI_TXM4_MASK   0x7
#define  fmux_gpio_funcsel_PAD_MIPI_TXP4   0x114
#define  fmux_gpio_funcsel_PAD_MIPI_TXP4_OFFSET 0
#define  fmux_gpio_funcsel_PAD_MIPI_TXP4_MASK   0x7
#define  fmux_gpio_funcsel_PAD_MIPI_TXM3   0x118
#define  fmux_gpio_funcsel_PAD_MIPI_TXM3_OFFSET 0
#define  fmux_gpio_funcsel_PAD_MIPI_TXM3_MASK   0x7
#define  fmux_gpio_funcsel_PAD_MIPI_TXP3   0x11c
#define  fmux_gpio_funcsel_PAD_MIPI_TXP3_OFFSET 0
#define  fmux_gpio_funcsel_PAD_MIPI_TXP3_MASK   0x7
#define  fmux_gpio_funcsel_PAD_MIPI_TXM2   0x120
#define  fmux_gpio_funcsel_PAD_MIPI_TXM2_OFFSET 0
#define  fmux_gpio_funcsel_PAD_MIPI_TXM2_MASK   0x7
#define  fmux_gpio_funcsel_PAD_MIPI_TXP2   0x124
#define  fmux_gpio_funcsel_PAD_MIPI_TXP2_OFFSET 0
#define  fmux_gpio_funcsel_PAD_MIPI_TXP2_MASK   0x7
#define  fmux_gpio_funcsel_PAD_MIPI_TXM1   0x128
#define  fmux_gpio_funcsel_PAD_MIPI_TXM1_OFFSET 0
#define  fmux_gpio_funcsel_PAD_MIPI_TXM1_MASK   0x7
#define  fmux_gpio_funcsel_PAD_MIPI_TXP1   0x12c
#define  fmux_gpio_funcsel_PAD_MIPI_TXP1_OFFSET 0
#define  fmux_gpio_funcsel_PAD_MIPI_TXP1_MASK   0x7
#define  fmux_gpio_funcsel_PAD_MIPI_TXM0   0x130
#define  fmux_gpio_funcsel_PAD_MIPI_TXM0_OFFSET 0
#define  fmux_gpio_funcsel_PAD_MIPI_TXM0_MASK   0x7
#define  fmux_gpio_funcsel_PAD_MIPI_TXP0   0x134
#define  fmux_gpio_funcsel_PAD_MIPI_TXP0_OFFSET 0
#define  fmux_gpio_funcsel_PAD_MIPI_TXP0_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX1_PAD0P   0x138
#define  fmux_gpio_funcsel_MIPIRX1_PAD0P_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX1_PAD0P_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX1_PAD0N   0x13c
#define  fmux_gpio_funcsel_MIPIRX1_PAD0N_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX1_PAD0N_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX1_PAD1P   0x140
#define  fmux_gpio_funcsel_MIPIRX1_PAD1P_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX1_PAD1P_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX1_PAD1N   0x144
#define  fmux_gpio_funcsel_MIPIRX1_PAD1N_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX1_PAD1N_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX1_PAD2P   0x148
#define  fmux_gpio_funcsel_MIPIRX1_PAD2P_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX1_PAD2P_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX1_PAD2N   0x14c
#define  fmux_gpio_funcsel_MIPIRX1_PAD2N_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX1_PAD2N_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX1_PAD3P   0x150
#define  fmux_gpio_funcsel_MIPIRX1_PAD3P_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX1_PAD3P_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX1_PAD3N   0x154
#define  fmux_gpio_funcsel_MIPIRX1_PAD3N_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX1_PAD3N_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX1_PAD4P   0x158
#define  fmux_gpio_funcsel_MIPIRX1_PAD4P_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX1_PAD4P_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX1_PAD4N   0x15c
#define  fmux_gpio_funcsel_MIPIRX1_PAD4N_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX1_PAD4N_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX0_PAD4N   0x160
#define  fmux_gpio_funcsel_MIPIRX0_PAD4N_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX0_PAD4N_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX0_PAD4P   0x164
#define  fmux_gpio_funcsel_MIPIRX0_PAD4P_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX0_PAD4P_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX0_PAD3N   0x168
#define  fmux_gpio_funcsel_MIPIRX0_PAD3N_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX0_PAD3N_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX0_PAD3P   0x16c
#define  fmux_gpio_funcsel_MIPIRX0_PAD3P_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX0_PAD3P_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX0_PAD2N   0x170
#define  fmux_gpio_funcsel_MIPIRX0_PAD2N_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX0_PAD2N_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX0_PAD2P   0x174
#define  fmux_gpio_funcsel_MIPIRX0_PAD2P_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX0_PAD2P_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX0_PAD1N   0x178
#define  fmux_gpio_funcsel_MIPIRX0_PAD1N_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX0_PAD1N_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX0_PAD1P   0x17c
#define  fmux_gpio_funcsel_MIPIRX0_PAD1P_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX0_PAD1P_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX0_PAD0N   0x180
#define  fmux_gpio_funcsel_MIPIRX0_PAD0N_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX0_PAD0N_MASK   0x7
#define  fmux_gpio_funcsel_MIPIRX0_PAD0P   0x184
#define  fmux_gpio_funcsel_MIPIRX0_PAD0P_OFFSET 0
#define  fmux_gpio_funcsel_MIPIRX0_PAD0P_MASK   0x7
#define  fmux_gpio_funcsel_VI_DATA22   0x188
#define  fmux_gpio_funcsel_VI_DATA22_OFFSET 0
#define  fmux_gpio_funcsel_VI_DATA22_MASK   0x7
#define  fmux_gpio_funcsel_VI_DATA20   0x18c
#define  fmux_gpio_funcsel_VI_DATA20_OFFSET 0
#define  fmux_gpio_funcsel_VI_DATA20_MASK   0x7
#define  fmux_gpio_funcsel_VI_DATA21   0x190
#define  fmux_gpio_funcsel_VI_DATA21_OFFSET 0
#define  fmux_gpio_funcsel_VI_DATA21_MASK   0x7
#define  fmux_gpio_funcsel_CAM_PD0   0x194
#define  fmux_gpio_funcsel_CAM_PD0_OFFSET 0
#define  fmux_gpio_funcsel_CAM_PD0_MASK   0x7
#define  fmux_gpio_funcsel_VI_DATA19   0x198
#define  fmux_gpio_funcsel_VI_DATA19_OFFSET 0
#define  fmux_gpio_funcsel_VI_DATA19_MASK   0x7
#define  fmux_gpio_funcsel_IIC0_SDA   0x19c
#define  fmux_gpio_funcsel_IIC0_SDA_OFFSET 0
#define  fmux_gpio_funcsel_IIC0_SDA_MASK   0x7
#define  fmux_gpio_funcsel_CAM_MCLK0   0x1a0
#define  fmux_gpio_funcsel_CAM_MCLK0_OFFSET 0
#define  fmux_gpio_funcsel_CAM_MCLK0_MASK   0x7
#define  fmux_gpio_funcsel_IIC3_SCL   0x1a4
#define  fmux_gpio_funcsel_IIC3_SCL_OFFSET 0
#define  fmux_gpio_funcsel_IIC3_SCL_MASK   0x7
#define  fmux_gpio_funcsel_VI_DATA24   0x1a8
#define  fmux_gpio_funcsel_VI_DATA24_OFFSET 0
#define  fmux_gpio_funcsel_VI_DATA24_MASK   0x7
#define  fmux_gpio_funcsel_CAM_RST0   0x1ac
#define  fmux_gpio_funcsel_CAM_RST0_OFFSET 0
#define  fmux_gpio_funcsel_CAM_RST0_MASK   0x7
#define  fmux_gpio_funcsel_VI_DATA23   0x1b0
#define  fmux_gpio_funcsel_VI_DATA23_OFFSET 0
#define  fmux_gpio_funcsel_VI_DATA23_MASK   0x7
#define  fmux_gpio_funcsel_IIC3_SDA   0x1b4
#define  fmux_gpio_funcsel_IIC3_SDA_OFFSET 0
#define  fmux_gpio_funcsel_IIC3_SDA_MASK   0x7
#define  fmux_gpio_funcsel_IIC0_SCL   0x1b8
#define  fmux_gpio_funcsel_IIC0_SCL_OFFSET 0
#define  fmux_gpio_funcsel_IIC0_SCL_MASK   0x7
