#!/bin/sh
${CVI_SHOPTS}

case "$1" in
  start)
    mkdir -p /mnt/data/log
    mount /mnt/data/log /var/log
    printf "Starting klogd: "
    start-stop-daemon -b -S -q --exec /sbin/klogd
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    printf "Starting syslogd: "
    start-stop-daemon -b -S -q --exec /sbin/syslogd -- -b 1 -s 64
    [ $? = 0 ] && echo "OK" || echo "FAIL"
  ;;
  stop)
    printf "Stopping logging: "
    start-stop-daemon -K -p /var/run/klogd.pid
    start-stop-daemon -K -p /var/run/syslogd.pid
    echo "OK"
    sleep 1
    umount /var/log
  ;;
  restart)
    printf "Restarting logging: "
    $0 stop
    sleep 1
    $0 start
    echo "OK"
  ;;
esac
