#!/bin/sh

case "$1" in
  start)
    printf "Starting msc: "
    /etc/uhubon.sh device
    /etc/run_usb.sh probe msc /dev/mmcblk0p1
    /etc/run_usb.sh start
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "Stopping msc: "
    echo "OK"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

