# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2023 Bitmain
#
obj-$(CONFIG_CVI_SOUND_DRIVERS)	+= cvi-sound.o
obj-$(CONFIG_CVI_SOUND_DRIVERS)	+= cvi-sound-uclass.o
obj-$(CONFIG_CVI_SOUND_DRIVERS)	+= cvi-dac-uclass.o
obj-$(CONFIG_CVI_SOUND_DRIVERS)	+= cvi-dac.o
obj-$(CONFIG_CVI_SOUND_DRIVERS)	+= cvi-i2s-uclass.o
obj-$(CONFIG_CVI_SOUND_DRIVERS)	+= cvi-i2s.o
