#
# Makefile for the Linux Wireless network device drivers for Realtek units
#

obj-$(CONFIG_RTL8188FU)     	+= rtl8188f/
obj-$(CONFIG_RTL8189FS)     	+= rtl8189fs/
obj-$(CONFIG_RTL8723DS)     	+= rtl8723ds/
obj-$(CONFIG_RTL8821CS)     	+= rtl8821cs/

